import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Votey</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-screen bg-slate-500">
        <div className="text-3xl text-center py-3 font-bold text-yellow-300 border-spacing-1 border-b border-yellow-300">
          <span className="cursor-pointer">Votey</span>
        </div>
        <section className="h-auto w-2/3 m-auto flex flex-col justify-center">
          <p className="font-extrabold text-5xl text-white my-5 text-center">
            {" "}
            Create your poll <br />{" "}
            <span className="text-yellow-300 border-b border-yellow-300">
              {" "}
              in seconds.{" "}
            </span>{" "}
          </p>
          <p className="text-3xl text-white text-center font-bold my-5">
            Want to ask your friends where to go friday night or arrange a
            meeting with co-workers? Create a poll - and get answers in no time.
          </p>
          <div className="text-center my-5">
            <Link href="/poll">
              <button className="py-2 px-4 bg-yellow-300 hover:bg-white font-bold rounded">
                {" "}
                Create a poll{" "}
              </button>
            </Link>
          </div>
        </section>
      </div>
    </div>
  );
};

export default Home;
